version: "3.8"

services:
  postgres_write:
    image: postgres:16
    container_name: postgres_write
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: profile_write
    ports:
      - "5433:5432"
    volumes:
      - pg_write_data:/var/lib/postgresql/data
    profiles:
      - minimal
      - full

  mongo_read:
    image: mongo:7
    container_name: mongo_read
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    profiles:
      - minimal
      - full

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_read
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_read:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongo_read
    profiles:
      - full

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: always
    environment:
      CLUSTER_ID: "QgS7Hq7hT7i4SlM0zvbYzw"
      KAFKA_CLUSTER_ID: "QgS7Hq7hT7i4SlM0zvbYzw"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_MIN_INSYNC_REPLICAS: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    ports:
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    profiles:
      - minimal
      - full

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka
    profiles:
      - full

  account-service-command:
    build:
      context: .
      dockerfile: AccountService/Command/Api/Dockerfile
    container_name: account-service-command
    ports:
      - "5222:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres_write
      - kafka
    profiles:
      - full

  account-service-query:
    build:
      context: .
      dockerfile: AccountService/Query/Api/Dockerfile
    container_name: account-service-query
    ports:
      - "5115:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo_read
      - kafka
    profiles:
      - full

  profile-service-command:
    build:
      context: .
      dockerfile: ProfileService/Command/Api/Dockerfile
    container_name: profile-service-command
    ports:
      - "5062:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres_write
      - kafka
    profiles:
      - full

  profile-service-query:
    build:
      context: .
      dockerfile: ProfileService/Query/Api/Dockerfile
    container_name: profile-service-query
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo_read
      - kafka
    profiles:
      - full

  time-service-command:
    build:
      context: .
      dockerfile: TimeService/Command/Api/Dockerfile
    container_name: time-service-command
    ports:
      - "5033:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres_write
      - kafka
    profiles:
      - full

  time-service-query:
    build:
      context: .
      dockerfile: TimeService/Query/Api/Dockerfile
    container_name: time-service-query
    ports:
      - "5257:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo_read
      - kafka
    profiles:
      - full

  evolution-service-command:
    build:
      context: .
      dockerfile: EvolutionService/Command/Api/Dockerfile
    container_name: evolution-service-command
    ports:
      - "5049:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres_write
      - kafka
    profiles:
      - full

  evolution-service-query:
    build:
      context: .
      dockerfile: EvolutionService/Query/Api/Dockerfile
    container_name: evolution-service-query
    ports:
      - "5011:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongo_read
      - kafka
    profiles:
      - full

volumes:
  pg_write_data:
  mongo_data:
  kafka_data:
